In [2]:
import pandas as pd
from pathlib import Path

RAW_DIR = Path("../data/raw")

In [3]:
unified_path = RAW_DIR / "ethiopia_fi_unified_data.xlsx"
xls = pd.ExcelFile(unified_path)
print(xls.sheet_names)

['ethiopia_fi_unified_data', 'Impact_sheet']

In [4]:
data_df = pd.read_excel(unified_path, sheet_name="ethiopia_fi_unified_data")
impact_df = pd.read_excel(unified_path, sheet_name="Impact_sheet")

print("data sheet shape:", data_df.shape)
print("impact sheet shape:", impact_df.shape)
data_df.head()

data sheet shape: (43, 34)
impact sheet shape: (14, 35)

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [5]:
ref_path = RAW_DIR / "reference_codes.xlsx"
guide_path = RAW_DIR / "Additional Data Points Guide.xlsx"

ref_df = pd.read_excel(ref_path)
print("reference_codes shape:", ref_df.shape)
ref_df.head()

reference_codes shape: (71, 4)

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

In [6]:
guide_xls = pd.ExcelFile(guide_path)
print(guide_xls.sheet_names)

['A. Alternative Baselines', 'B. Direct Corrln', 'C. Indirect Corrln', 'D. Market Naunces']

In [7]:
print("Record type counts:")
print(data_df["record_type"].value_counts())

print("\nPillar counts (data sheet):")
print(data_df["pillar"].value_counts(dropna=False))

if "source_type" in data_df.columns:
    print("\nSource type counts:")
    print(data_df["source_type"].value_counts(dropna=False))

if "confidence" in data_df.columns:
    print("\nConfidence level counts:")
    print(data_df["confidence"].value_counts(dropna=False))

Record type counts:
record_type
observation    30
event          10
target          3
Name: count, dtype: int64

Pillar counts (data sheet):
pillar
ACCESS           16
USAGE            11
NaN              10
GENDER            5
AFFORDABILITY     1
Name: count, dtype: int64

Source type counts:
source_type
operator      15
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2
Name: count, dtype: int64

Confidence level counts:
confidence
high      40
medium     3
Name: count, dtype: int64

In [8]:
date_col = "observation_date" if "observation_date" in data_df.columns else "date"
print("Date range:", data_df[date_col].min(), "to", data_df[date_col].max())

print("\nUnique indicators and their record counts:")
print(data_df["indicator_code"].value_counts(dropna=False))

Date range: 2014-12-31 00:00:00 to 2030-12-31 00:00:00

Unique indicators and their record counts:
indicator_code
ACC_OWNERSHIP         7
ACC_FAYDA             4
ACC_MM_ACCOUNT        2
ACC_4G_COV            2
USG_P2P_COUNT         2
GEN_GAP_ACC           2
GEN_MM_SHARE          2
ACC_MOBILE_PEN        1
USG_P2P_VALUE         1
USG_ATM_COUNT         1
USG_ATM_VALUE         1
USG_CROSSOVER         1
USG_TELEBIRR_USERS    1
USG_TELEBIRR_VALUE    1
USG_MPESA_USERS       1
USG_MPESA_ACTIVE      1
USG_ACTIVE_RATE       1
AFF_DATA_INCOME       1
GEN_GAP_MOBILE        1
EVT_TELEBIRR          1
EVT_SAFARICOM         1
EVT_MPESA             1
EVT_FAYDA             1
EVT_FX_REFORM         1
EVT_CROSSOVER         1
EVT_MPESA_INTEROP     1
EVT_ETHIOPAY          1
EVT_NFIS2             1
EVT_SAFCOM_PRICE      1
Name: count, dtype: int64

In [9]:
events_df = data_df[data_df["record_type"] == "event"]
events_df[["record_id", "category", date_col, "notes"]]

   record_id        category observation_date  notes
33  EVT_0001  product_launch       2021-05-17    NaN
34  EVT_0002    market_entry       2022-08-01    NaN
35  EVT_0003  product_launch       2023-08-01    NaN
36  EVT_0004  infrastructure       2024-01-01    NaN
37  EVT_0005          policy       2024-07-29    NaN
38  EVT_0006       milestone       2024-10-01    NaN
39  EVT_0007     partnership       2025-10-27    NaN
40  EVT_0008  infrastructure       2025-12-18    NaN
41  EVT_0009          policy       2021-09-01    NaN
42  EVT_0010         pricing       2025-12-15    NaN

In [10]:
obs_df = data_df[data_df["record_type"] == "observation"]

print("Observation date range:", obs_df[date_col].min(), "to", obs_df[date_col].max())

print("\nIndicator coverage (observations only):")
print(obs_df["indicator_code"].value_counts())

Observation date range: 2014-12-31 00:00:00 to 2025-12-31 00:00:00

Indicator coverage (observations only):
indicator_code
ACC_OWNERSHIP         6
ACC_FAYDA             3
ACC_MM_ACCOUNT        2
ACC_4G_COV            2
USG_P2P_COUNT         2
GEN_GAP_ACC           2
ACC_MOBILE_PEN        1
USG_P2P_VALUE         1
USG_ATM_COUNT         1
USG_ATM_VALUE         1
USG_CROSSOVER         1
USG_TELEBIRR_USERS    1
USG_TELEBIRR_VALUE    1
USG_MPESA_USERS       1
USG_MPESA_ACTIVE      1
USG_ACTIVE_RATE       1
AFF_DATA_INCOME       1
GEN_MM_SHARE          1
GEN_GAP_MOBILE        1
Name: count, dtype: int64

In [11]:
impact_joined = impact_df.merge(
    events_df[["record_id", "category", date_col]],
    left_on="parent_id", right_on="record_id",
    suffixes=("", "_event")
)
impact_joined[["parent_id", "category", "pillar", "related_indicator",
               "impact_direction", "impact_magnitude", "lag_months", "evidence_basis"]]

,parent_id,category,pillar,related_indicator,impact_direction,impact_magnitude,lag_months,evidence_basis
0,EVT_0001,NaN,ACCESS,ACC_OWNERSHIP,increase,high,12,literature
1,EVT_0001,NaN,USAGE,USG_TELEBIRR_USERS,increase,high,3,empirical
2,EVT_0001,NaN,USAGE,USG_P2P_COUNT,increase,high,6,empirical
3,EVT_0002,NaN,ACCESS,ACC_4G_COV,increase,medium,12,empirical
4,EVT_0002,NaN,AFFORDABILITY,AFF_DATA_INCOME,decrease,medium,12,literature
5,EVT_0003,NaN,USAGE,USG_MPESA_USERS,increase,high,3,empirical
6,EVT_0003,NaN,ACCESS,ACC_MM_ACCOUNT,increase,medium,6,theoretical
7,EVT_0004,NaN,ACCESS,ACC_OWNERSHIP,increase,medium,24,literature
8,EVT_0004,NaN,GENDER,GEN_GAP_ACC,decrease,medium,24,literature
9,EVT_0005,NaN,AFFORDABILITY,AFF_DATA_INCOME,increase,high,3,empirical
10,EVT_0007,NaN,USAGE,USG_MPESA_ACTIVE,increase,medium,3,literature
11,EVT_0007,NaN,USAGE,USG_P2P_COUNT,increase,medium,3,literature
12,EVT_0008,NaN,USAGE,USG_P2P_COUNT,increase,medium,6,literature
13,EVT_0010,NaN,AFFORDABILITY,AFF_DATA_INCOME,increase,low,1,empirical

In [12]:
print(list(data_df.columns))
print(list(impact_df.columns))

['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']
['record_id', 'parent_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

In [14]:
import numpy as np

def next_ids(df, prefix, n):
    existing_nums = df["record_id"].str.extract(r"(\d+)")[0].astype(int)
    start = existing_nums.max() + 1
    return [f"{prefix}_{i:04d}" for i in range(start, start + n)]

today = pd.Timestamp("2026-07-19")

def make_record(**kwargs):
    row = {col: np.nan for col in data_df.columns}
    row.update(kwargs)
    return row

print("helpers ready")

helpers ready

In [15]:
import numpy as np

# Helper: find next available record_id number so we never collide with existing ones
def next_ids(df, prefix, n):
    existing_nums = df["record_id"].str.extract(r"(\d+)")[0].astype(int)
    start = existing_nums.max() + 1
    return [f"{prefix}_{i:04d}" for i in range(start, start + n)]

today = pd.Timestamp("2026-07-19")

# Base template — every field defaults to NaN unless set per-record
def make_record(**kwargs):
    row = {col: np.nan for col in data_df.columns}
    row.update(kwargs)
    return row

new_observations = [
    make_record(record_type="observation", pillar="GENDER", indicator="Account Ownership Rate",
                indicator_code="ACC_OWNERSHIP", value_numeric=36, unit="percentage",
                gender="female", observation_date="2024-12-31", source_name="Global Findex 2025 (via Shega)",
                source_type="survey", source_url="https://shega.co/news/findex-2025-and-ethiopias-digital-financial-leap-momentum-without-maturity",
                confidence="high", collected_by="Rebe", collection_date=today,
                notes="Women's account ownership 2024 Findex; gender gap component"),
    make_record(record_type="observation", pillar="GENDER", indicator="Account Ownership Rate",
                indicator_code="ACC_OWNERSHIP", value_numeric=56, unit="percentage",
                gender="male", observation_date="2024-12-31", source_name="Global Findex 2025 (via Shega)",
                source_type="survey", source_url="https://shega.co/news/findex-2025-and-ethiopias-digital-financial-leap-momentum-without-maturity",
                confidence="high", collected_by="Rebe", collection_date=today,
                notes="Men's account ownership 2024 Findex; gender gap component"),
    make_record(record_type="observation", pillar="USAGE", indicator="Mobile Money Account Ownership",
                indicator_code="ACC_MM_ACCOUNT", value_numeric=19.4, unit="percentage",
                observation_date="2025-12-31", source_name="Global Findex 2025 (via Shega)",
                source_type="survey", source_url="https://shega.co/news/findex-2025-and-ethiopias-digital-financial-leap-momentum-without-maturity",
                confidence="high", collected_by="Rebe", collection_date=today,
                notes="Mobile money account ownership quadrupled from 4.7% (2021) to 19.4% (2025)"),
    make_record(record_type="observation", pillar="ACCESS", indicator="4G Population Coverage",
                indicator_code="ACC_4G_COV", value_numeric=70.8, unit="percentage",
                observation_date="2025-06-30", source_name="Ethio Telecom / GSMA", source_type="operator",
                source_url="https://en.wikipedia.org/wiki/Ethio_Telecom", confidence="medium",
                collected_by="Rebe", collection_date=today,
                notes="Single-operator (Ethio Telecom) 4G coverage, up from 33% in 2023 — not full-market figure"),
    # Fayda digital ID enrollment time series
    make_record(record_type="observation", pillar="ACCESS", indicator="Fayda Digital ID Enrollment",
                indicator_code="ACC_FAYDA", value_numeric=15, unit="millions",
                observation_date="2025-05-31", source_name="ID4Africa 2025 / ID Tech", source_type="operator",
                source_url="https://idtechwire.com/ethiopia-launches-fayda-digital-id-system-to-cover-90-million-citizens-by-2027/",
                confidence="high", collected_by="Rebe", collection_date=today, notes="Fayda enrollment as of May 2025"),
    make_record(record_type="observation", pillar="ACCESS", indicator="Fayda Digital ID Enrollment",
                indicator_code="ACC_FAYDA", value_numeric=16.4, unit="millions",
                observation_date="2025-06-04", source_name="Biometric Update", source_type="operator",
                source_url="https://www.biometricupdate.com/202607/ethiopia-partners-with-safaricom-to-run-digital-id-enrollment-in-7-regions",
                confidence="high", collected_by="Rebe", collection_date=today, notes="Fayda enrollment as of June 4, 2025"),
    make_record(record_type="observation", pillar="ACCESS", indicator="Fayda Digital ID Enrollment",
                indicator_code="ACC_FAYDA", value_numeric=28, unit="millions",
                observation_date="2025-11-01", source_name="EBC", source_type="news",
                source_url="https://www.ebc.et/english/Home/NewsDetails?NewsId=2981",
                confidence="high", collected_by="Rebe", collection_date=today,
                notes="Fayda enrollment ~Nov 2025; target 60M by mid-2026"),
    make_record(record_type="observation", pillar="ACCESS", indicator="Fayda Digital ID Enrollment",
                indicator_code="ACC_FAYDA", value_numeric=46.5, unit="millions",
                observation_date="2026-07-12", source_name="Biometric Update", source_type="operator",
                source_url="https://www.biometricupdate.com/202607/ethiopia-partners-with-safaricom-to-run-digital-id-enrollment-in-7-regions",
                confidence="high", collected_by="Rebe", collection_date=today, notes="Most recent Fayda enrollment figure"),
    # P2P vs ATM crossover, FY2024/25 (same-year pair, avoids mixing fiscal years)
    make_record(record_type="observation", pillar="USAGE", indicator="P2P Transaction Value",
                indicator_code="USG_P2P_VALUE", value_numeric=577.7, unit="billion_birr", fiscal_year="2024/25",
                source_name="EthSwitch Annual Report (via The Reporter Ethiopia)", source_type="operator",
                source_url="https://www.thereporterethiopia.com/47608/", confidence="high",
                collected_by="Rebe", collection_date=today, notes="128.3M P2P transactions, FY2024/25"),
    make_record(record_type="observation", pillar="USAGE", indicator="ATM Withdrawal Value",
                indicator_code="USG_ATM_VALUE", value_numeric=156, unit="billion_birr", fiscal_year="2024/25",
                source_name="EthSwitch Annual Report (via The Reporter Ethiopia)", source_type="operator",
                source_url="https://www.thereporterethiopia.com/47608/", confidence="high",
                collected_by="Rebe", collection_date=today, notes="~120M ATM withdrawals, FY2024/25; P2P value now exceeds this"),
]

# New event: EthioPay unified payment brand launch
new_events = [
    make_record(record_type="event", category="product_launch",
                observation_date="2025-12-01", source_name="Capital Newspaper", source_type="news",
                source_url="https://capitalethiopia.com/2025/12/21/ethswitch-launches-ethiopay-to-unify-national-digital-paymentsby-our-staff-reporter/",
                confidence="medium", collected_by="Rebe", collection_date=today,
                notes="EthSwitch launched 'Ethiopay' unified national digital payment brand integrating mobile/digital payment services"),
]

new_obs_ids = next_ids(data_df, "REC", len(new_observations))
new_evt_ids = next_ids(data_df, "REC", len(new_events))  # computed after concat below to avoid collision

In [16]:
print(f"{len(new_observations)} new observations built")
print(f"{len(new_events)} new events built")
print(new_obs_ids)
print(new_evt_ids)

10 new observations built
1 new events built
['REC_0034', 'REC_0035', 'REC_0036', 'REC_0037', 'REC_0038', 'REC_0039', 'REC_0040', 'REC_0041', 'REC_0042', 'REC_0043']
['REC_0034']

In [17]:
# Fix ID collision: events get the next IDs after all the observations
new_evt_ids = next_ids(pd.DataFrame({"record_id": data_df["record_id"].tolist() + new_obs_ids}),
                        "REC", len(new_events))

for rec, rid in zip(new_observations, new_obs_ids):
    rec["record_id"] = rid
for rec, rid in zip(new_events, new_evt_ids):
    rec["record_id"] = rid

print("Event ID:", new_evt_ids)  # will need this for the impact_link parent_id

# Merge into main dataset
enriched_data_df = pd.concat(
    [data_df, pd.DataFrame(new_observations), pd.DataFrame(new_events)],
    ignore_index=True
)

print("Original data_df shape:", data_df.shape)
print("Enriched data_df shape:", enriched_data_df.shape)

Event ID: ['REC_0044']
Original data_df shape: (43, 34)
Enriched data_df shape: (54, 34)

In [19]:
def make_impact_record(**kwargs):
    row = {col: np.nan for col in impact_df.columns}
    row.update(kwargs)
    return row

new_impact_ids = next_ids(pd.DataFrame({"record_id": impact_df["record_id"].tolist()}), "IMP", 3)

new_impact_links = [
    # Closes the gap: EVT_0006 (P2P/ATM crossover milestone) had no impact_link before
    make_impact_record(record_id=new_impact_ids[0], parent_id="EVT_0006", record_type="impact_link",
                        pillar="USAGE", related_indicator="USG_CROSSOVER", relationship_type="milestone_confirmation",
                        impact_direction="increase", impact_magnitude="high", lag_months=0,
                        evidence_basis="empirical", collected_by="Rebe", collection_date=today,
                        source_name="EthSwitch Annual Report / Capital Newspaper",
                        source_url="https://capitalethiopia.com/2025/11/02/ethswitch-reports-historic-growth-as-p2p-payments-surpass-atm-withdrawals/",
                        confidence="high",
                        notes="P2P interoperable transaction volume exceeded ATM withdrawal volume for first time, Oct 2024; P2P value also surpassed ATM value in FY24/25"),
    # New EthioPay launch event -> likely effects (theoretical, not yet observed - it's a Dec 2025 launch)
    make_impact_record(record_id=new_impact_ids[1], parent_id="REC_0044", record_type="impact_link",
                        pillar="USAGE", related_indicator="USG_P2P_COUNT", relationship_type="event_impact",
                        impact_direction="increase", impact_magnitude="medium", lag_months=6,
                        evidence_basis="theoretical", collected_by="Rebe", collection_date=today,
                        source_name="Capital Newspaper",
                        source_url="https://capitalethiopia.com/2025/12/21/ethswitch-launches-ethiopay-to-unify-national-digital-paymentsby-our-staff-reporter/",
                        confidence="low",
                        notes="EthioPay brand unification launched Dec 2025; too recent for empirical evidence, estimate is theoretical based on stated goal of unifying fragmented digital payment services"),
    make_impact_record(record_id=new_impact_ids[2], parent_id="REC_0044", record_type="impact_link",
                        pillar="ACCESS", related_indicator="ACC_MM_ACCOUNT", relationship_type="event_impact",
                        impact_direction="increase", impact_magnitude="low", lag_months=12,
                        evidence_basis="theoretical", collected_by="Rebe", collection_date=today,
                        source_name="Capital Newspaper",
                        source_url="https://capitalethiopia.com/2025/12/21/ethswitch-launches-ethiopay-to-unify-national-digital-paymentsby-our-staff-reporter/",
                        confidence="low",
                        notes="Unified branding may reduce friction/confusion across mobile money providers, modestly aiding account adoption"),
]

enriched_impact_df = pd.concat([impact_df, pd.DataFrame(new_impact_links)], ignore_index=True)

print("Original impact_df shape:", impact_df.shape)
print("Enriched impact_df shape:", enriched_impact_df.shape)

# Save to data/processed/
processed_dir = Path("../data/processed")
processed_dir.mkdir(exist_ok=True)

with pd.ExcelWriter(processed_dir / "ethiopia_fi_unified_data_enriched.xlsx") as writer:
    enriched_data_df.to_excel(writer, sheet_name="ethiopia_fi_unified_data", index=False)
    enriched_impact_df.to_excel(writer, sheet_name="Impact_sheet", index=False)

print("Saved to:", processed_dir / "ethiopia_fi_unified_data_enriched.xlsx")

Original impact_df shape: (14, 35)
Enriched impact_df shape: (17, 35)
Saved to: ..\data\processed\ethiopia_fi_unified_data_enriched.xlsx

In [20]:
# Verify the saved file is readable and has the right shape
check = pd.read_excel(processed_dir / "ethiopia_fi_unified_data_enriched.xlsx", sheet_name=None)
print("Sheets found:", list(check.keys()))
print("data sheet shape:", check["ethiopia_fi_unified_data"].shape)
print("Impact_sheet shape:", check["Impact_sheet"].shape)

Sheets found: ['ethiopia_fi_unified_data', 'Impact_sheet']
data sheet shape: (54, 34)
Impact_sheet shape: (17, 35)

In [21]:
log_lines = ["# Data Enrichment Log", "", f"Generated {today.date()} by Rebika", ""]

log_lines.append("## New Observations (10)")
for rec in new_observations:
    log_lines.append(f"- **{rec['record_id']}** | {rec['indicator_code']} = {rec['value_numeric']} {rec['unit']} "
                      f"({rec.get('observation_date', rec.get('fiscal_year', 'n/a'))}) "
                      f"| confidence: {rec['confidence']} | source: {rec['source_name']}")
    log_lines.append(f"  - Notes: {rec['notes']}")
    log_lines.append(f"  - URL: {rec['source_url']}")

log_lines.append("\n## New Events (1)")
for rec in new_events:
    log_lines.append(f"- **{rec['record_id']}** | category: {rec['category']} | date: {rec['observation_date']} "
                      f"| confidence: {rec['confidence']} | source: {rec['source_name']}")
    log_lines.append(f"  - Notes: {rec['notes']}")
    log_lines.append(f"  - URL: {rec['source_url']}")

log_lines.append("\n## New Impact Links (3)")
for rec in new_impact_links:
    log_lines.append(f"- **{rec['record_id']}** | {rec['parent_id']} → {rec['related_indicator']} "
                      f"({rec['impact_direction']}, {rec['impact_magnitude']}, lag {rec['lag_months']}mo) "
                      f"| evidence: {rec['evidence_basis']} | confidence: {rec['confidence']}")
    log_lines.append(f"  - Notes: {rec['notes']}")

log_lines.append("\n## Data Quality Notes")
log_lines.append("- Real observation date range (excluding target rows): 2014-12-31 to 2025-12-31")
log_lines.append("- Most indicators have only 1-2 data points; only ACC_OWNERSHIP (6) and ACC_FAYDA (now 7 with enrichment) support real trend analysis")
log_lines.append("- EVT_0006 previously had no impact_link — now filled with empirical evidence (see above)")
log_lines.append("- EVT_0009 (policy, 2021-09-01) still has no impact_link — no quantified before/after effect found; documented as a genuine data gap, not estimated")

log_path = Path("../data_enrichment_log.md")
log_path.write_text("\n".join(log_lines), encoding="utf-8")
print("Log written to:", log_path.resolve())

Log written to: C:\Users\pc\ethiopia-fi-forecast\data_enrichment_log.md